name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout test repo
      uses: actions/checkout@v2
      with:
        repository: IvanYuliyanov/testrepository
        path: testrepository

    - name: Copy file test
      run: cp test.txt IvanYuliyanov/testrepository/test.txt

    - name: Build with Gradle
      run: ./gradlew build
