name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Checkout test repo
      uses: actions/checkout@v2
      with:
        repository: IvanYuliyanov/private-repo
        token: ${{ secrets.COOKERY_SECRET }}
        path: private-repo

    - name: Copy file test
      run: cp private-repo/README.md README.md

    - name: Build
      run: ./gradlew build
